### PR TITLE
Fix concurrency problems in IgnoreDictionary and SettingStore

### PR DESCRIPTION
**Pull request by napalu**
(fixes erratic concurrency exceptions observed in certain test environments)

### CODE REVIEW

**Comment by chaowlert** [comment]
I haven't merge yet because
1. I need to check dependency for .net core 1.x (yes I still support that)
2. I don't think this is main root cause for collision, `TypeAdapterConfig`  should be.
3. I also not sure I should add this, unit test should be isolate. We should declare new `TypeAdapterConfig`  for every method.

**Comment by napalu** [comment]
On Fri, 2020-06-05 at 16:45 -0700, chaowlert wrote:
Hi 
The fixes were introduced after I started seeing sporadic (that is,
occurring on certain but not all test runs) failures after upgrading
from Mapster 4.x to 5.3.2
We were getting randomly occurring errors using our test harness such
as:
System.NullReferenceException : Object reference not set to an instance
of an object.   at
System.Collections.Generic.Dictionary`2.FindEntry(TKey key)   at
System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue&
value)   at
Mapster.Utils.CoreExtensions.GetValueOrDefault[T,U](IDictionary`2 dict,
T key)   at Mapster.SettingStore.Get[T](String key, Func`1
initializer)   at Mapster.TypeAdapterSettings.get_Ignore()   at
Mapster.TypeAdapterSetter`1.Ignore(Expression`1[] members)   at
Mapster.TypeAdapterSetter`2.Ignore(Expression`1[] members)
On another run:   System.NullReferenceException : Object reference not
set to an instance of an object.  Stack Trace:     at
System.Collections.Generic.Dictionary`2.FindEntry(TKey key)   at
System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue&
value)   at
Mapster.Utils.CoreExtensions.GetValueOrDefault[T,U](IDictionary`2 dict,
T key)   at Mapster.SettingStore.Get[T](String key, Func`1
initializer)   at Mapster.TypeAdapterSettings.get_Resolvers()   at
Mapster.TypeAdapterSetter`2.Map[TDestinationMember,TSourceMember](Expre
ssion`1 member, Expression`1 source, Expression`1 shouldMap)
Or yet another run:  Error Message:   System.InvalidOperationException
: Operations that change non-concurrent collections must have exclusive
access. A concurrent update was performed on this collection and
corrupted its state. The collection's state is no longer correct. 
Stack Trace:     at
System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue
value, InsertionBehavior behavior)   at
Mapster.TypeAdapterSetter`1.Ignore(Expression`1[] members)   at
Mapster.TypeAdapterSetter`2.Ignore(Expression`1[] members)

Since using the changes in the fork fixed the randomly occurring errors
for us.

 
> I haven't merge yet because
> 
> I need to check dependency for .net core 1.x (yes I still support
> that)
> I don't think this is main root cause for collision,
> TypeAdapterConfig  should be.
> I also not sure I should add this, unit test should be isolate. We
> should declare new TypeAdapterConfig  for every method.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 
napalu gmbh
Zwinglistrasse 5
Ch-8004 Zürich
Tel: +41.76 399 77 61

**Comment by chaowlert** [comment]
Thx u for info, I will take a look soon.

**Comment by Dreamescaper** [comment]
Have same issue. It happens not in unit tests, but in integration tests using TestHost, where multiple test environments are created in parallel. And, since mappings are initialized statically, that leads to concurrency errors.

**Pull request merged**
