### PR TITLE
Upgraded to .Net 7

### PR DESCRIPTION
**Pull request by SefaOray**
This PR upgrades all project within the solution to .Net 7. This is created to address the issue: 

https://github.com/MapsterMapper/Mapster/issues/475

### CODE REVIEW

**Comment by oscarjaergren** [comment]
Would love to get a new release with this

**Comment by cedwards-telis** [comment]
This PR still has old references that cause issues with ef 7.0.  Obviously you can use ef core 6.0 with .net 7.0 but you might want to run ef 7.0.

https://github.com/SefaOray/Mapster/blob/development/src/Mapster.EFCore/packages.config

Line 3 should be

  <package id="EntityFramework" version="7.0.0" />

And 

https://github.com/SefaOray/Mapster/blob/development/src/Mapster.EFCore/Mapster.EFCore.csproj

Line 15 should be

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0" />

If you don't do this and run with ef 7.0 you'll get exceptions like

System.MissingMethodException: 'Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.' due to conflicting versions.

I suppose that there is a way to handle complex mixed version packages but I don't know it....

**Comment by HenricFranssonXM** [comment]
Do you have a release plan for official .Net 7 support?

**Comment by cedwards-telis** [comment]
Actually I think the issue I am having with

System.MissingMethodException: 'Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.' due to conflicting versions.

may be because the verison of the ef core plugin on Nuget was not complied on the right version of ef core - https://github.com/dotnet/efcore/issues/26701#issuecomment-1054881574

**Comment by andrerav** [comment]
Fixed by #496. Thank you @SefaOray!

**Pull request closed without merging**
