### PR TITLE
Include .NET 6.0 as Target Framework for Mapster.Tool

### LINKED ISSUE #381: ef core 6.x support
I would like to request support for ef core 6.x in the ef core plug in.

### PR DESCRIPTION
**Pull request by kaizen365**
Resolves #381

### CODE REVIEW

**Review by mo3in — APPROVED** [review]
merge it please.

and if possible we can use .net source generator for the future

**Comment by patrikmolsson** [comment]
What is preventing the merge of this PR?

We would really appreciate getting this in, since it's blocking our migration to .NET 6. 

@chaowlert , @SergerGood

**Comment by andrerav** [comment]
Just chiming in to show my support for merging this ASAP as well as following up with an updated Nuget package. @chaowlert @eswann @SergerGood

**Comment by frasermclean** [comment]
Any reason this 1 line PR is taking so long to merge?

**Comment by SergerGood** [comment]
@frasermclean I have no right to do this

**Comment by andrerav** [comment]
@chaowlert Have you had a time to look at this?

**Comment by prezek** [comment]
Please, could someone merge this change?

**Comment by kaizen365** [comment]
Not sure if @chaowlert is still around? looks like he's been away for the last 6 months?
Might need to fork this project and issue a nuget release?

As a workaround for anyone else, simply pull this branch, bump the version #, compile, publish locally a nupkg and add locally...

**Review by eswann — APPROVED** [review]

**Comment by eswann** [comment]
Hey @kaizen365 , @patrikmolsson, @andrerav, @frasermclean, @SergerGood, @mo3in, I merged the PR, but it's been years since I've contributed to this project, and I haven't worked in the .Net space in a few years as well. I'm not sure what build procedures @chaowlert has been using to publish these packages out to Nuget and frankly I don't have the bandwidth currently to figure it out. 
It looks like @chaowlert has gone dark for several months now, so I only hope that his health is OK. I would be happy to try to set up somebody else to do the necessary work if anyone would like to volunteer.

**Comment by byme8** [comment]
@eswann Looks like I managed to build and generate the Nuget packages for Mapster. It was pretty straightforward.

```
git clone git@github.com:MapsterMapper/Mapster.git
cd ./Mapster/src
// change the nuget version number in the ./src/Mapster.Tool/Mapster.Tool.csproj from 8.2.0 to 8.2.1
dotnet build -c Release
dotnet pack -c Release -o ./out
```
After that, I should have a bunch of the Nuget packages in the ``~/src/out/`` folder. As I understood, you need the Mapster.Tool.8.3.0.nupkg. It can be uploaded directly to nuget.org.

**Comment by eswann** [comment]
@byme8 Yeah that would be the manual way, but I know I would have automated it to some extent back when I worked on this thing. I see a deploy directory using psake (not sure if that's still used).

**Comment by SergerGood** [comment]
Hey, @eswann. I could do this, but I need permissions to work with the project.

**Pull request merged**
